[project]
name = "comfyui-nkd-preview-tools"
description = "Preview tools for ComfyUI: a floating popup preview window (multi-monitor friendly) and a wireless reference image to compare against."
version = "2.6.0"
license = { file = "LICENSE.txt" }
dependencies  = []

[project.urls]
Repository = "https://github.com/Nekodificador/ComfyUI-NKD-Preview-Tools"

[tool.comfy]
PublisherId = "nekodificador"
DisplayName = "NKD Preview Tools"
Icon = ""
